-- scripts/regress-format.lua — unit tests for the format-on-save safety
-- policy (modules.utils.format_skip_reason): vendor/, generated files,
-- module cache, user disabled-dirs are skipped; ordinary project files
-- (incl. /tmp scratch) are formatted.
--
-- Run:  nvim --headless --noplugin -u NONE \
--          --cmd "set rtp+=<repo-root>" -l scripts/regress-format.lua
-- Exit 0 when all cases pass, 1 otherwise. No network, no user config.

local failures = 0
local total = 0

local function check(desc, cond)
	total = total + 1
	if cond then
		print("OK " .. desc)
	else
		failures = failures + 1
		print("FAIL " .. desc)
	end
end

local utils = require("modules.utils")
local skip = utils.format_skip_reason

-- Ordinary project files are never skipped.
check("project file ok", skip("/home/u/proj/main.go", {}) == nil)
check("tmp scratch ok", skip("/tmp/x.go", {}) == nil)
check("windows project ok", skip("C:\\work\\proj\\main.go", {}) == nil)
check("nested pkg ok", skip("/home/u/proj/inner/a.go", {}) == nil)
-- Vendor directories (either separator, any depth, any case drive).
check("vendor unix", skip("/home/u/proj/vendor/lib/a.go", {}) == "vendor")
check("vendor windows", skip("C:\\work\\proj\\vendor\\lib\\a.go", {}) == "vendor")
check("vendor nested", skip("/home/u/proj/sub/vendor/x/y.go", {}) == "vendor")
check("vendorlike file kept", skip("/home/u/proj/myvendor/a.go", {}) == nil)
-- Generated files by suffix.
check("pb.go", skip("/home/u/proj/a.pb.go", {}) == "generated")
check("pb.gw.go", skip("/home/u/proj/a.pb.gw.go", {}) == "generated")
check("generated suffix", skip("/home/u/proj/z_generated.go", {}) == "generated")
check("gen suffix", skip("/home/u/proj/z.gen.go", {}) == "generated")
check("plain go kept", skip("/home/u/proj/gen.go", {}) == nil)
-- Module cache / toolchain (is_go_lib coverage).
check("gomodcache", skip("/home/u/go/pkg/mod/lib/a.go", {}) == "module-cache")
check("gomodcache windows", skip("D:\\work\\gopath\\pkg\\mod\\lib@ver\\a.go", {}) == "module-cache")
check("goroot", skip("/usr/local/go/src/fmt/a.go", {}) == "module-cache")
check("goroot windows", skip("C:\\Program Files\\Go\\src\\fmt\\a.go", {}) == "module-cache")
-- User disabled dirs (vim regex, normalized).
check("disabled dir", skip("/home/u/secret/a.go", { "/home/u/secret" }) == "disabled-dir")
check("disabled dir windows", skip("C:\\work\\no\\a.go", { "C:/work/no" }) == "disabled-dir")
check("other dir kept", skip("/home/u/other/a.go", { "/home/u/secret" }) == nil)
-- Generated marker in buffer head.
do
	local buf = vim.api.nvim_create_buf(false, true)
	vim.api.nvim_buf_set_lines(buf, 0, -1, false, {
		"// Code generated by MockGen. DO NOT EDIT.",
		"package mocks",
	})
	check("generated marker", skip("/home/u/proj/mock_foo.go", {}, buf) == "generated")
	vim.api.nvim_buf_delete(buf, { force = true })
end
do
	local buf = vim.api.nvim_create_buf(false, true)
	vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "package hand", "// handwritten" })
	check("handwritten kept", skip("/home/u/proj/mock_foo.go", {}, buf) == nil)
	vim.api.nvim_buf_delete(buf, { force = true })
end
-- Empty path is not a skip (untitled buffers handled elsewhere).
check("empty path", skip("", {}) == nil)

print(string.format("total=%d failures=%d", total, failures))
if failures > 0 then
	os.exit(1)
end
